export interface AppTheme {
  id: string;
  name: string;
  // 'light' themes switch MUI's palette mode so default component colors stay
  // legible on light backgrounds. Defaults to 'dark' when absent.
  mode?: 'dark' | 'light';
  colors: {
    primary: string;
    secondary: string;
    background: string;
    surface: string;
    surfaceAlt: string;
    text: string;
    textSecondary: string;
    border: string;
    error: string;
    success: string;
    warning: string;
    info: string;
  };
}

export const themes: AppTheme[] = [
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    colors: {
      primary: '#00f0ff',
      secondary: '#ff2d78',
      background: '#0a0a0f',
      surface: '#12121a',
      surfaceAlt: '#1a1a28',
      text: '#e8e8f0',
      textSecondary: '#7a7a90',
      border: '#1e1e30',
      error: '#ff4060',
      success: '#00ff88',
      warning: '#ffb800',
      info: '#00c8ff',
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    colors: {
      primary: '#00ff88',
      secondary: '#8b5cf6',
      background: '#0d1117',
      surface: '#161b22',
      surfaceAlt: '#1c2333',
      text: '#e6edf3',
      textSecondary: '#7d8590',
      border: '#21262d',
      error: '#ff5555',
      success: '#00ff88',
      warning: '#f0c000',
      info: '#58a6ff',
    },
  },
  {
    id: 'ember',
    name: 'Ember',
    colors: {
      primary: '#ff6b35',
      secondary: '#ffd700',
      background: '#121218',
      surface: '#1a1a24',
      surfaceAlt: '#222230',
      text: '#f0ece4',
      textSecondary: '#8a8490',
      border: '#2a2a38',
      error: '#ff4444',
      success: '#44ff88',
      warning: '#ffd700',
      info: '#ff8855',
    },
  },
  {
    id: 'frost',
    name: 'Frost',
    colors: {
      primary: '#4fc3f7',
      secondary: '#e0e0e0',
      background: '#0f1923',
      surface: '#1a2636',
      surfaceAlt: '#223344',
      text: '#e4eaf0',
      textSecondary: '#7a8ea0',
      border: '#263848',
      error: '#ff5566',
      success: '#44ddaa',
      warning: '#ffcc44',
      info: '#4fc3f7',
    },
  },
  {
    id: 'void',
    name: 'Void',
    colors: {
      primary: '#a855f7',
      secondary: '#84cc16',
      background: '#000000',
      surface: '#0a0a0a',
      surfaceAlt: '#141414',
      text: '#f0f0f0',
      textSecondary: '#6a6a7a',
      border: '#1a1a1a',
      error: '#ff3355',
      success: '#84cc16',
      warning: '#eab308',
      info: '#a78bfa',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    colors: {
      primary: '#22d3ee',
      secondary: '#3b82f6',
      background: '#0b1220',
      surface: '#111c33',
      surfaceAlt: '#18243f',
      text: '#e2e8f0',
      textSecondary: '#64748b',
      border: '#1e2d4d',
      error: '#ff4d6d',
      success: '#34d399',
      warning: '#fbbf24',
      info: '#38bdf8',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    colors: {
      primary: '#fb7185',
      secondary: '#fb923c',
      background: '#150b14',
      surface: '#20121f',
      surfaceAlt: '#2c1826',
      text: '#fbeef1',
      textSecondary: '#93707e',
      border: '#3a2033',
      error: '#f87171',
      success: '#4ade80',
      warning: '#facc15',
      info: '#f472b6',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    colors: {
      primary: '#34d399',
      secondary: '#a3e635',
      background: '#0a120c',
      surface: '#101b12',
      surfaceAlt: '#17271a',
      text: '#e7f0ea',
      textSecondary: '#6f8a78',
      border: '#1f3326',
      error: '#f87171',
      success: '#34d399',
      warning: '#facc15',
      info: '#5eead4',
    },
  },
  {
    id: 'royal',
    name: 'Royal',
    colors: {
      primary: '#c084fc',
      secondary: '#f0abfc',
      background: '#120b1f',
      surface: '#1b1330',
      surfaceAlt: '#251a40',
      text: '#f3edf9',
      textSecondary: '#8d7fb5',
      border: '#32245a',
      error: '#fb7185',
      success: '#a3e635',
      warning: '#fde047',
      info: '#a78bfa',
    },
  },
  {
    id: 'matrix',
    name: 'Matrix',
    colors: {
      primary: '#00ff66',
      secondary: '#00ccff',
      background: '#020b03',
      surface: '#07130a',
      surfaceAlt: '#0c1f11',
      text: '#d8f5e2',
      textSecondary: '#5f8f6e',
      border: '#12331f',
      error: '#ff3355',
      success: '#00ff66',
      warning: '#ffee00',
      info: '#00ccff',
    },
  },

  // --- Light themes ---

  {
    id: 'daylight',
    name: 'Daylight',
    mode: 'light',
    colors: {
      primary: '#1976d2',
      secondary: '#00897b',
      background: '#f4f7fb',
      surface: '#ffffff',
      surfaceAlt: '#eef2f7',
      text: '#1a2332',
      textSecondary: '#5b6b81',
      border: '#d7dde6',
      error: '#d32f2f',
      success: '#2e7d32',
      warning: '#ed6c02',
      info: '#0288d1',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    mode: 'light',
    colors: {
      primary: '#455a64',
      secondary: '#757575',
      background: '#fafaf6',
      surface: '#ffffff',
      surfaceAlt: '#f1f1ea',
      text: '#2c2c2c',
      textSecondary: '#757575',
      border: '#e0e0d8',
      error: '#c62828',
      success: '#2e7d32',
      warning: '#f9a825',
      info: '#546e7a',
    },
  },
  {
    id: 'sky',
    name: 'Sky',
    mode: 'light',
    colors: {
      primary: '#0288d1',
      secondary: '#7e57c2',
      background: '#e8f4fd',
      surface: '#ffffff',
      surfaceAlt: '#e1f0fb',
      text: '#0e2a3d',
      textSecondary: '#5b7a91',
      border: '#c9e2f2',
      error: '#d32f2f',
      success: '#2e7d32',
      warning: '#f57c00',
      info: '#0288d1',
    },
  },
  {
    id: 'mint',
    name: 'Mint',
    mode: 'light',
    colors: {
      primary: '#00897b',
      secondary: '#43a047',
      background: '#ecf7f3',
      surface: '#ffffff',
      surfaceAlt: '#dff1ea',
      text: '#10332d',
      textSecondary: '#4f7a70',
      border: '#c5e2d8',
      error: '#d32f2f',
      success: '#2e7d32',
      warning: '#f9a825',
      info: '#00897b',
    },
  },
  {
    id: 'blossom',
    name: 'Blossom',
    mode: 'light',
    colors: {
      primary: '#d81b60',
      secondary: '#8e24aa',
      background: '#fdf1f5',
      surface: '#ffffff',
      surfaceAlt: '#fbe4ec',
      text: '#3c1a28',
      textSecondary: '#8c5b6e',
      border: '#f0cdd9',
      error: '#c62828',
      success: '#2e7d32',
      warning: '#ef6c00',
      info: '#ab47bc',
    },
  },
  {
    id: 'ivory',
    name: 'Ivory',
    mode: 'light',
    colors: {
      primary: '#8d6e63',
      secondary: '#a1887f',
      background: '#faf8f3',
      surface: '#ffffff',
      surfaceAlt: '#f4f0e8',
      text: '#3b2f2a',
      textSecondary: '#7d6f67',
      border: '#e3dcd2',
      error: '#c62828',
      success: '#558b2f',
      warning: '#ef6c00',
      info: '#6d4c41',
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    mode: 'light',
    colors: {
      primary: '#7c4dff',
      secondary: '#b388ff',
      background: '#f4f0fb',
      surface: '#ffffff',
      surfaceAlt: '#ece6f7',
      text: '#2a2340',
      textSecondary: '#6b6287',
      border: '#ddd4f0',
      error: '#c62828',
      success: '#2e7d32',
      warning: '#f57c00',
      info: '#7c4dff',
    },
  },
  {
    id: 'sage',
    name: 'Sage',
    mode: 'light',
    colors: {
      primary: '#2e7d32',
      secondary: '#81c784',
      background: '#f1f7ef',
      surface: '#ffffff',
      surfaceAlt: '#e6f0e3',
      text: '#223325',
      textSecondary: '#5c7060',
      border: '#cfe0cb',
      error: '#c62828',
      success: '#2e7d32',
      warning: '#ef6c00',
      info: '#558b2f',
    },
  },
  {
    id: 'peach',
    name: 'Peach',
    mode: 'light',
    colors: {
      primary: '#e64a19',
      secondary: '#ff8a65',
      background: '#fdf4ef',
      surface: '#ffffff',
      surfaceAlt: '#fbe9e1',
      text: '#3d2419',
      textSecondary: '#8a6252',
      border: '#f2d5c6',
      error: '#c62828',
      success: '#2e7d32',
      warning: '#f57c00',
      info: '#e64a19',
    },
  },
  {
    id: 'oceanlight',
    name: 'Ocean Light',
    mode: 'light',
    colors: {
      primary: '#00695c',
      secondary: '#26a69a',
      background: '#eef7f8',
      surface: '#ffffff',
      surfaceAlt: '#dff1f2',
      text: '#12302e',
      textSecondary: '#4f6f6d',
      border: '#c2dfe1',
      error: '#c62828',
      success: '#2e7d32',
      warning: '#f57c00',
      info: '#00897b',
    },
  },
];

export const getThemeById = (id: string): AppTheme => {
  return themes.find((t) => t.id === id) || themes[0];
};
